### ISSUE TITLE
Not a Hash Function

### ISSUE THREAD

**Issue by ironstrider** [CaselIT/hash-set-map#1]
What is referred to as a hash function isn't a proper hash function, since hashes should be able to collide - see the first example in Wikipedia's [Hash function entry](https://en.wikipedia.org/wiki/Hash_function).

It's really a key serialisation function - i.e. it maps a key to another unique key, and is useful because it can map an unhashable key to a hashable key. This should be made clear in the readme, as calling it a hash function is misleading.

```
const {Map} = require("hash-set-map")

const m = new Map([[1, 1], [2, 4], [3, 9], [4, 16]], d => d % 3);

m.get(1) // => should be 1, but returns 16, since 1 % 3 === 4 % 3
```

**Comment by CaselIT** [comment]
Thanks for the observation!
I agree, sadly I'm not very good at naming things. 

I'll update the readme to clarify it

**Comment by CaselIT** [comment]
I'm not sure if a new npm release is warranted for this change. What do you think?
